3-interface
shved/homework pull request #3
Opened 2020-10-29 14:34 UTC by shved

Насколько я понял, использовать нашу заглушку паука пока что не надо, поэтому никакого теста с ее использованием нет. Рядом с пакетом spider сделал пакет spidermock который реализует интерфейс Scanner

2020-10-31 10:44 UTC, DmitriyVTitov commented
> Насколько я понял, использовать нашу заглушку паука пока что не надо, поэтому никакого теста с ее использованием нет.

Я это не написал в задании, и уже править поздно. Но, конечно, неиспользуемого кода быть не должно!

2020-10-31 10:49 UTC, DmitriyVTitov requested changes
Интерфейс нигде не используется. Я на 3-х занятиях и многократно в Слаке объяснял как используются в коде интерфейсы, но тема сложная.
Если это всё ещё вызывает трудности - спрашивайте в Слаке, в общем канале. Вы далеко не единственный.

2020-10-31 10:49 UTC, DmitriyVTitov commented on 3-interface/cmd/main.go
> +}
интерфейс нигде не используется!

2020-10-31 10:49 UTC, DmitriyVTitov commented on 3-interface/pkg/spider/spider.go
> +}
т.е. одноразовый сканер, который может распарсить только один сайт?

2020-10-31 10:49 UTC, DmitriyVTitov commented on 3-interface/pkg/spider/spider.go
> +func (s *Spider) Scan() (data map[string]string, err error) {
откуда берёт данные (ссылку, например) функция Scan не понятно. зачем было так её переделывать тоже не ясно.

2020-11-04 18:05 UTC, shved commented
Я переработал main.go так чтобы интерфейс использовался в нем.

2020-11-06 09:11 UTC, DmitriyVTitov approved these changes
Принято!

2020-11-06 09:11 UTC, DmitriyVTitov commented on 3-interface/cmd/engine/main.go
> +}
ОК

2020-11-06 09:11 UTC, DmitriyVTitov commented on 3-interface/cmd/engine/main.go
> +	s := spider.New(2)
2, а что 2? :)

2020-11-06 09:11 UTC, DmitriyVTitov commented on 3-interface/cmd/engine/main.go
> +
пустая строка

2020-11-06 09:11 UTC, DmitriyVTitov commented on 3-interface/cmd/engine/main.go
> +	fmt.Println(" Done.")
такие надписи в функциях не нужны

2020-11-06 09:11 UTC, DmitriyVTitov commented on 3-interface/cmd/engine/main.go
> +func scan(s Scanner, store map[string]string, url string) (map[string]string, error) {
сама идея возвращать модифицированный аргумент `store` не очень. лучше пусть функция возвращает хэш-таблицу с новыми данными (создвёт таблицу сама).
а вызывающий код уже решит - добавлять их куда-то или нет.
т.е. аргумент `store` тут ни к чему.

2020-11-06 09:11 UTC, DmitriyVTitov commented on 3-interface/pkg/spidermock/spidermock.go
> +}
вот этот код следовало использовать в тесте для функции `scan` из пакета `main`

2020-11-11 18:36 UTC, merged