4-index
shved/homework pull request #4
Opened 2020-11-11 18:39 UTC by shved

Вроде сделал все норм, посмотрел на ваш набросок финальной программы в гитхабе, оттуда кое что подсмотрел тоже. Единственное что не понял, и там не увидел тоже - это где таки использовать бинарный поиск. Я вообще не использую айдишники, храню в GIN урлы, и по ним же достаю документы. По памяти выходит накладно конечно.

2020-11-15 00:56 UTC, DmitriyVTitov commented
> Вроде сделал все норм, посмотрел на ваш набросок финальной программы в гитхабе, оттуда кое что подсмотрел тоже. Единственное что не понял, и там не увидел тоже - это где таки использовать бинарный поиск. Я вообще не использую айдишники, храню в GIN урлы, и по ним же достаю документы. По памяти выходит накладно конечно.

Из задания:

> Документы должны быть представлены в виде структуры данных. При этом для каждого документа нужно добавить его номер – поле в структуре данных вместе с URL и Title.

Индекс возвращает номера документов. Вот по массиву документов и надо искать бинарным поиском (ищется документ по номеру).

2020-11-15 00:59 UTC, DmitriyVTitov requested changes
1. Не реализована функция поиска.
2. Не выполнены требования задания.

2020-11-15 00:59 UTC, DmitriyVTitov commented on 4-index/pkg/index/index.go
> +	GIN   map[string][]string
неправильно, задание требует номеров документов.
во-первых, это значительно выгоднее по памяти.
во-вторых, поиск также значительно быстрей (числа против строк).

2020-11-15 19:38 UTC, shved commented
Вставил бинарный поиск из стдлибы, переделал на хранение айдишек.

2020-11-17 05:04 UTC, DmitriyVTitov approved these changes
Принято!

2020-11-17 05:04 UTC, DmitriyVTitov commented on 4-index/cmd/websearch/main.go
> +
опять пустая строка просто так?

2020-11-17 05:04 UTC, DmitriyVTitov commented on 4-index/pkg/index/index.go
> +		s.curID++
```
s.curID++
doc.ID = s.curID
```

2020-11-17 05:04 UTC, DmitriyVTitov commented on 4-index/pkg/index/index.go
> +		if len(words) > 0 { // title may contain only stop words
бессмысленное условие, там в функции `range`.

2020-11-17 05:04 UTC, DmitriyVTitov commented on 4-index/pkg/index/index.go
> +}
откуда тут ошибка взялась?
ну не найден документ, и что?

2020-11-17 08:02 UTC, merged